<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBsIONE1\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBsIONE1/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBsIONE1.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBsIONE1\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerBsIONE1\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'BsIONE1',
    'container.build_id' => '7fb70d95',
    'container.build_time' => 1575019086,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBsIONE1');
