<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPsK75AE\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPsK75AE/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPsK75AE.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPsK75AE\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPsK75AE\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'PsK75AE',
    'container.build_id' => 'a37d26b6',
    'container.build_time' => 1574759227,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPsK75AE');
